---
:server: irc.freenode.net

:nick: elfari
:channels:
  - "#foobarslkj"
:timeout: 10

:elfari:
  :url: 'localhost'
  :port: 4567
:mplayer: '/usr/bin/mplayer'

:database: 'config/db/database'
:apm: 'config/db/apm'
:apm_folder: 'config/db/apm_songs'
:melee:
  :channel: "#foobarslkj chan-key"

:internet_song: 'config/tracks/internet_down.ogg'

:vlc:
  :bin: '/usr/bin/vlc'
  :host: '0.0.0.0'
  :port: 4000
  :args: '--ignore-config -I lua --lua-intf cli --no-video'

:mpd_url: '127.0.0.1'
:mpd_port: 6600

:twitter:
  :lang: 'es'
  :screen_names: 'screen_name1,term2' # Comma separated
  :channel: '#foobarslkj'
